services:
  web:
    image: fpfis/httpd-php:8.2-dev
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DOCUMENT_ROOT: ${PWD}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      # XDEBUG_CONFIG: "client_host=172.18.176.1"
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "develop, debug"
  mysql:
    image: percona/percona-server:8.0
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  # vnc in http://localhost:7900/
  selenium:
    image: selenium/standalone-chrome:4.1.3
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1000
      - SCREEN_HEIGHT=575
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    shm_size: 2g
volumes:
  mysql:
  #nameserver 172.27.144.1
