version: '3.7'
services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-dev
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DOCUMENT_ROOT: ${PWD}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "develop, debug"
  mysql:
    image: percona/percona-server:5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql
  # Spawn a Selenium server which also includes a VNC server on localhost:5900 (the password is "secret")
  selenium:
    image: selenium/standalone-chrome:4.1.3
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1600
      - SCREEN_HEIGHT=1200
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
    expose:
      - '4444'
    shm_size: 2g
volumes:
  mysql:
