version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.4
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      DOCUMENT_ROOT: ${PWD}
      # Remove comments XDEBUG_CONFIG, XDEBUG_MODE and PHP_IDE_CONFIG and rebuild the container to enable xdebug.
      # XDEBUG_CONFIG: "client_host=host.docker.internal" # Mac users.
      # XDEBUG_MODE: "debug"
      # PHP_IDE_CONFIG: "serverName=Docker"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
  mysql:
    image: percona/percona-server:5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  data:
  mysql: