version: "3.7"
services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    #container_name: "${PROJECT_NAME}_php"
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD} 
    environment:
      # Remove comments XDEBUG_CONFIG, XDEBUG_MODE and PHP_IDE_CONFIG and rebuild the container to enable xdebug.
      XDEBUG_CONFIG: "client_host=host.docker.internal" # Mac users.
      XDEBUG_MODE: "debug"
      PHP_IDE_CONFIG: "serverName=Docker"
      #SSMTP_MAILHUB: mailhog:1025
      #SSMTP_MAILHUB: opensmtpd:26
      #PHP_SENDMAIL_PATH: '"/usr/bin/dos2unix -u | /usr/sbin/ssmtp -t -f"'
      #DB_HOST: $DB_HOST
      #DB_PORT: $DB_PORT
      #DB_USER: $DB_USER
      #DB_PASSWORD: $DB_PASSWORD
      #DB_NAME: $DB_NAME
      #DB_DRIVER: $DB_DRIVER
      #DRUSH_OPTIONS_URI: "http://${PROJECT_BASE_URL}:${PROJECT_PORT}"
      #PHP_FPM_USER: wodby
      #PHP_FPM_GROUP: wodby
      #COLUMNS: 80 # Set 80 columns for docker exec -it.
      ## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
      #PHP_XDEBUG: 1
      #PHP_XDEBUG_MODE: debug
      #PHP_IDE_CONFIG: serverName=my-ide
      #PHP_XDEBUG_IDEKEY: "my-ide"
      #PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
      #PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      #PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows, Docker < 18.03
      #PHP_XDEBUG_LOG: /tmp/php-xdebug.log
      ## PHPUnit Drupal testing configurations
      #SIMPLETEST_BASE_URL: "http://nginx"
      #SIMPLETEST_DB: "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}#tests_"
      #MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
  ## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/drupal/local#docker-for-mac
  #    - drupal:/var/www/html
  ## For XHProf and Xdebug profiler traces
  #    - files:/mnt/files
  apache:
    image: wodby/apache:$APACHE_TAG
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
  #    container_name: "${PROJECT_NAME}_apache"
    depends_on:
      - php
    environment:
      APACHE_INDEXES_ENABLED: 1
      APACHE_DOCUMENT_ROOT: ${PWD}
      APACHE_LOG_LEVEL: debug
      APACHE_VHOST_PRESET: ${PWD}
  #      APACHE_BACKEND_HOST: php
  #      APACHE_VHOST_PRESET: php
  #      APACHE_DOCUMENT_ROOT: /var/www/html/web
  #    volumes:
  #    - ./:/var/www/html:cached
  ## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/drupal/local#docker-for-mac
  #    - drupal:/var/www/html
  #    labels:
  #    - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"
  
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    # container_name: "${PROJECT_NAME}_mariadb"
    #container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      # MYSQL_DATABASE: $DB_NAME
      # MYSQL_USER: $DB_USER
      # MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - mariadb:/var/lib/mariadb
    ports:
      - 3306:3306
 
volumes:
#  data:
  mariadb:
